# Generated by Django 4.0 on 2021-12-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobPositions',
            new_name='JobPosition',
        ),
    ]
